= Readme: Layout of the release notes project directory

This directory provides configuration for a release notes documentation project. It uses the aCoRNs tool to generate release notes from Bugzilla and Jira tickets.

* The `main-template.adoc` file is the central AsciiDoc file. It includes both generated and manually written content. You can compile it using the following two wrappers.

* The `main-external.adoc` file is a wrapper around `main-template.adoc`. It enables you to select an external preview of the documentation.

* The `main-internal.adoc` file is a wrapper around `main-template.adoc`. It enables you to select an internal preview of the documentation.

* The `manual-content/` directory contains manually written AsciiDoc content that you can include from the main file.

* The `acorns/` directory contains generator configuration files and generated AsciiDoc content that you can include from the main file:

`acorns/tickets.yaml`::
Lists the tickets and ticket queries that populate your release notes.

`acorns/tracker.yaml`::
Configures access to your Bugzilla and Jira instance.

`acorns/templates.yaml`::
Configures how your tickets are organized into sections of the document.

`acorns/generated/external/` and `acorns/generated/internal/`::
Store the generated assemblies and modules. These directories strictly contain only generated content, and the directories appear when aCoRNs has generated documentation files.
+
At every run, aCoRNs removes and recreates these files. Do not save manual content here.
