:toc: left
:name: Cizrna
:bin-name: cizrna

= Generating release notes using {name}

== Installing {name}

. Enable the {name} package repository:
+
[subs="+quotes,+attributes"]
----
# dnf copr enable mareksu/{bin-name}
----

. Install the package:
+
[subs="+quotes,+attributes"]
----
# dnf install {bin-name}
----

== Building release notes

. Navigate to your release notes project:
+
[subs=+quotes]
----
$ cd _my-release-notes_
----

. Set your API keys for Bugzilla and Jira:
+
[subs=+quotes]
----
$ export BZ_API_KEY=__my-bugzilla-key__
$ export JIRA_API_KEY=__my-jira-key__
----

. Generate release notes:
+
[subs="+quotes,+attributes"]
----
$ {bin-name} build
----

. Compile the AsciiDoc files:
+
----
$ asciidoctor --safe -vn main.adoc
----

. Preview the document:
+
----
$ gio open main.html
----

////
. Switch between the internal and external (public) version of the document. Use either of the following ways:

** When building the document, add the `--attribute=variant=internal` or `--attribute=variant=public` option on the command line.
** In the `main.adoc` file, edit the line that says `:variant: internal` to `:variant: public`, or vice versa.
////

== Differences between {name} and CoRN

Compare the different format of the configuration files:

* `corn-template` and `{bin-name}/templates.yaml`

* `corn.yaml` and `{bin-name}/tickets.yaml`

Also compare the structure of the generated files:

* `corn-generated-external/` and `{bin-name}/generated/`

== Known issues and limitations

See the issues in the {name} repository: link:https://github.com/msuchane/{bin-name}/issues[].

