:toc: left
:name: Cizrna
:bin-name: cizrna

= Generating release notes using {name}

== Installing {name}

* On Fedora, CentOS Stream, or RHEL, use link:https://copr.fedorainfracloud.org/coprs/mareksu/cizrna/[the Copr repository]:

.. Enable the repository:
+
----
# dnf copr enable mareksu/cizrna
----

.. Install the `cizrna` package:
+
----
# dnf install cizrna
----

* On any system that has the Docker or Podman container platform, you can use {name} as a container.
+
On Fedora, RHEL, and CentOS, replace `docker` with `podman` in the following commands.

.. Download the image:
+
----
$ docker pull quay.io/msuchane/cizrna
----

.. Configure a command alias. Save this line in your shell configuration file, such as in the `~/.bashrc` file:
+
----
alias cizrna="docker run -it -e BZ_API_KEY -e JIRA_API_KEY -v .:/mnt/cizrna:Z msuchane/cizrna cizrna"
----

.. Open a new terminal to reload the shell configuration.

* On any system, including different Linux distributions and macOS, you can build {name} from source:

.. Install the Rust toolchain se described at <https://rustup.rs/>.

.. Build and install {name} from its Git repository:
+
----
$ cargo install --git https://github.com/msuchane/cizrna/
----
+
If the build fails due to a missing dependency, install the missing dependency on your system and start the build again.

== Creating a new release notes project

. Create all configuration files that are necessary to generate release notes using {name}:
+
[subs="+quotes,+attributes"]
----
$ {bin-name} init __path-to-directory__
----
+
Replace `__path-to-directory__` with the directory where you want to store your release notes configuration.

. Examine the generated directory.
+
This directory provides a demo of a release notes documentation project. It uses the Cizrna tool to generate release notes from Bugzilla and Jira tickets.

** The `master_template.adoc` file is the main AsciiDoc file. It includes both generated and manually written content.

** The `master_internal.adoc` and `master_external.adoc` files are wrappers around `master_template.adoc`. They enable you to select between an internal preview and a public version of the documentation.

** The `manual-sections` directory contains manually written AsciiDoc content that you can include from the main file.

** The `cizrna/` directory contains generator configuration files and generated AsciiDoc content that you can include from the main file:

*** `cizrna/tickets.yaml` lists the tickets and ticket queries that populate your release notes.

*** `cizrna/tracker.yaml` configures access to your Bugzilla and Jira instance.

*** `cizrna/templates.yaml` configures how your tickets are sorted into sections of the document.

*** `cizrna/generated/internal/` and `cizrna/generated/internal/` store the generated assemblies and modules.


== Building release notes

. Navigate to your release notes project:
+
[subs=+quotes]
----
$ cd _my-release-notes_
----

. Set your API keys for Bugzilla and Jira:
+
[subs=+quotes]
----
$ export BZ_API_KEY=__my-bugzilla-key__
$ export JIRA_API_KEY=__my-jira-key__
----

. Generate release notes:
+
[subs="+quotes,+attributes"]
----
$ {bin-name} build
----

. Compile the AsciiDoc files:
+
----
$ asciidoctor --safe -vn main.adoc
----

. Preview the document:
+
----
$ gio open main.html
----

////
. Switch between the internal and external (public) version of the document. Use either of the following ways:

** When building the document, add the `--attribute=variant=internal` or `--attribute=variant=public` option on the command line.
** In the `main.adoc` file, edit the line that says `:variant: internal` to `:variant: public`, or vice versa.
////

== Differences between {name} and CoRN

Compare the different format of the configuration files:

* `corn-template` and `{bin-name}/templates.yaml`

* `corn.yaml` and `{bin-name}/tickets.yaml`

Also compare the structure of the generated files:

* `corn-generated-external/` and `{bin-name}/generated/`

== Known issues and limitations

See the issues in the {name} repository: link:https://github.com/msuchane/{bin-name}/issues[].

