:_newdoc-version: 2.15.0
:_template-generated: 2023-10-30
:_mod-docs-content-type: PROCEDURE

[id="adding-an-explanatory-footnote-to-private-tickets_{context}"]
= Adding an explanatory footnote to private tickets

[role="_abstract"]
Public ticket IDs  contain a clickable link to the ticket. Private ticket IDs are non-clickable. If this is confusing to the readers, you can automatically generate a footnote next to private ticket IDs that explains why the ticket link is missing.

For example:

* link:https://bugzilla.redhat.com/show_bug.cgi?id=2157953[Bugzilla:2157953]
* Bugzilla:2216257footnoteref:[PrivateTicketFootnote,This ticket is private.]

.Prerequisites

* Prepare the text that you want to add to every private ticket ID as a footnote.

.Procedure

. In your release notes project, enter a footnote with the `PrivateTicketFootnote` ID in a manually written AsciiDoc file.
+
The footnote must appear before you include the first file generated by {name}, such as near the book introduction or at the start of the main file.
+
.Placement of the footnote in main.adoc
====
[source,asciidoc"]
----
= Release notes for {Product} {Version}

This is the abstract paragraph.

Release notes include links where you can access the original tracking ticket. Private tickets have no links and instead feature ýžzuuuuujuzzzzzzzzzzzz´´´´´´´´´´´´´
----
====

. Include one command or action for each step with the exception of simple follow-step, for example:
.. Do this thing and then select *Next*.
.. Do this other thing and then select *Next*.

. Use an unnumbered bullet (*) if the procedure includes only one step.

.Verification

Delete this section if it does not apply to your module. Provide the user with verification methods for the procedure, such as expected output or commands that confirm success or failure.

* Provide an example of expected command output or a pop-up window that the user receives when the procedure is successful.
* List actions for the user to complete, such as entering a command, to determine the success or failure of the procedure.
* Make each step an instruction.
* Include one command or action per step.
* Use an unnumbered bullet (*) if the verification includes only one step.

[role="_additional-resources"]
.Next steps

* This section is optional.
* Provide a bulleted list of links that contain instructions that might be useful to the user after they complete this procedure.
* Use an unnumbered bullet (*) if the list includes only one step.

NOTE: Do not use *Next steps* to provide a second list of instructions.

[role="_additional-resources"]
.Additional resources

* This section is optional.
* Provide a bulleted list of links to other closely-related material. These links can include `link:` and `xref:` macros.
* Use an unnumbered bullet (*) if the list includes only one step.

