:_content-type: PROCEDURE

[id="configuring-access-to-your-ticket-trackers_{context}"]
= Configuring access to your ticket trackers

The default, sample project configuration tries to access ticket trackers that do not exist. Configure your release notes project to connect with trackers that host your tickets.

For the purpose of this document, a _ticket tracker_ is either *Bugzilla* or *Jira*. In the future, {name} might add support for additional trackers or remove support for current ones.

.Prerequisites

* You have installed {name}.
* You have initialized a directory with sample release notes project configuration.

.Procedure

. Navigate to your release notes project:
+
[subs=+quotes]
----
$ cd _my-release-notes_
----

. Open the `{bin-name}/trackers.yaml` file in an editor.

. Configure access to your Bugzilla and Jira instance.
+
NOTE: Currently, {name} requires configuration for both trackers. If you are only using one, you can enter empty, invalid values for the other, unused trackers. {name} only uses the configuration on demand.

** In the `bugzilla` section, fill out the following, required fields for Bugzilla:
+
[source,yaml]
----
bugzilla:
  host: "https://bugzilla.host.org"
  fields:
    doc_type:
      - "cf_doc_type"
    doc_text:
      - "cf_release_notes"
    doc_text_status:
      - "requires_doc_text"
----
+
`host`:: The base URL to your Bugzilla instance.
`doc_type`:: The code name of the *Doc Type* field, which is probably a drop-down menu of values.
`doc_text`:: The code name of the *Doc Text* field, which is a text box that contains your release note.
`doc_text_status`:: The code name of the flag that describes the status of the release note.


** In the `jira` section, fill out the following, required fields for Jira:
+
[source,yaml]
----
jira:
  host: "https://jira.host.org"
  fields:
    doc_type:
      - "customfield_12345678"
    doc_text:
      - "customfield_23456789"
    doc_text_status:
      - "customfield_34567890"
    docs_contact:
      - "customfield_45678901"
----
+
`host`:: The base URL to your Jira instance.
`doc_type`:: The code name of the field that lists the type of the release note. It is a drop-down menu of values.
`doc_text`:: The code name of the field that contains your release note. It is a text box.
`doc_text_status`:: The code name of the field that lists the status of the release note. It is a drop-down menu of values.

.Verification

. Add tickets to your release notes project.

. Build the release notes.


[role="_additional-resources"]
.Additional resources
* xref:identifying-field-code-names-in-jira_{context}[]
* xref:required-and-optional-fields-in-tracker-configuration_{context}[]
