:_content-type: PROCEDURE

[id="building-release-notes_{context}"]
= Building release notes

Build a release notes project in a local directory that contains your {name} configuration files.

.Prerequisites

* You have installed {name}.
* You have configured access to your tickets trackers.
* You have added tickets to your release notes project configuration.

.Procedure

. Navigate to your release notes project:
+
[subs=+quotes]
----
$ cd _my-release-notes_
----

. Set your API keys for Bugzilla and Jira:
+
[subs=+quotes]
----
$ export BZ_API_KEY=__my-bugzilla-key__

$ export JIRA_API_KEY=__my-jira-key__
----
+
If you are using a shell that is not compatible with the Bourne shell syntax, adjust the commands.
+
For example, with the Fish shell:
+
[subs=+quotes]
----
$ set -x BZ_API_KEY=__my-bugzilla-key__

$ set -x JIRA_API_KEY __my-jira-key__
----

. Generate release notes:
+
[subs="+quotes,+attributes"]
----
$ {bin-name} build
----

. Compile the external and internal version of the AsciiDoc document:
+
----
$ asciidoctor --safe -vn main.adoc

$ asciidoctor --safe -vn internal.adoc
----

. Open the `main.html` and `internal.html` files in a web browser to preview the document.
+
In the GNOME desktop environment, you can use the following commands:
+
----
$ gio open main.html

$ gio open internal.html
----
