:_newdoc-version: 2.15.0
:_template-generated: 2023-10-30
:_mod-docs-content-type: PROCEDURE

:private-footnote-text: This ticket is private.

[id="adding-an-explanatory-footnote-to-private-tickets_{context}"]
= Adding an explanatory footnote to private tickets

[role="_abstract"]
Public ticket IDs  contain a clickable link to the ticket. Private ticket IDs are non-clickable. If this is confusing to the readers, you can automatically generate a footnote next to private ticket IDs that explains why the ticket link is missing.

.Procedure

. Prepare the text that you want to add to every private ticket ID as a footnote. For example:
+
[source,asciidoc]
----
This ticket is private.
----

. In your release notes project, enter a footnote with the `PrivateTicketFootnote` ID in a manually written AsciiDoc file.
+
The footnote must appear before you include the first file generated by {name}, such as near the book introduction or at the start of the main file. This requirement is caused by a technical limitation in the deprecated `footnoteref` macro.
+
You can store the footnote text in a separate attribute, so that it is more convenient to edit:
+
.Placement of the footnote in main.adoc
====
[source,asciidoc"]
----
:private-footnote-text: This ticket is private.

= Release notes for {Product} {Version}

This is the abstract paragraph.

Release notes include links to access the original tracking tickets. Private tickets have no links and instead feature the following footnote{blank}footnoteref:[PrivateTicketFootnote,{private-footnote-text}].

<Include your modules here.>
----
====

.Verification

. Build the release notes project.
. Open a preview.
. Compare the IDs of public and private tickets. Verify that all private tickets feature the footnote.
+
For example:

** link:https://bugzilla.redhat.com/show_bug.cgi?id=2157953[Bugzilla:2157953]
** Bugzilla:2216257{blank}footnoteref:[PrivateTicketFootnote,{private-footnote-text}]

[role="_additional-resources"]
.Additional resources

* If you want to hide all links to certain Jira projects and set them as private, see `private_projects` in xref:required-and-optional-fields-in-tracker-configuration_enabling-access-to-your-ticket-trackers[].
