:_content-type: PROCEDURE

[id="sorting-tickets-in-your-project-using-templates_{context}"]
= Sorting tickets in your project using templates

WARNING: This is currently just a template and a placeholder. The documentation will appear later.

The default, sample project configuration sorts your release notes based on their doc type, as found in the tickets. You can configure your templates to sort release notes in a custom way, such as into sections nested by doc type and component.

.Prerequisites

* A bulleted list of conditions that must be satisfied before the user starts the steps in this module.
* Prerequisites can be full sentences or sentence fragments; however, prerequisite list items must be parallel.

.Procedure

. Make each step an instruction.

. Include one command or action for each step with the exception of simple follow-step, for example:
.. Do this thing and then select *Next*.
.. Do this other thing and then select *Next*.

. Use an unnumbered bullet (*) if the procedure includes only one step.

.Verification

. Provide an example of expected command output or a pop-up window that the user receives when the procedure is successful.

. List actions for the user to complete, such as entering a command, to determine the success or failure of the procedure.

. Make each step an instruction.

. Include one command or action per step.

. Use an unnumbered bullet (*) if the verification includes only one step.

[role="_additional-resources"]
.Additional resources
* A bulleted list of links to other closely-related material. These links can include `link:` and `xref:` macros.
* For more details on writing procedure modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].

